#    Copyright (C) 2013 Alexandros Avdis and others. See the AUTHORS file for a full list of copyright holders.
#
#    This file is part of qmesh-cli.
#
#    qmesh-cli is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    qmesh-cli is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with qmesh-cli.  If not, see <http://www.gnu.org/licenses/>.

# enable Docker
options:
  docker: true

definitions:
  caches:
    docker-dir-cache: /var/lib/docker/ 

pipelines:
  branches:
    master:
      - step:
          caches:
            # Cache directory where all docker images are stored.
            - docker-dir-cache
          script:
            - export QMESH_CLI_VERSION=`cat VERSION`
            - export IMAGE_NAME=qmesh/qmesh-containers:qmesh-cli${QMESH_VERSION}_ubuntu16.04_qgisltr_gmsh3.0.4
            # Build container (install qmesh and test)
            - docker build -t $IMAGE_NAME ./tests/
            # authenticate with the Docker Hub registry
            - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
            # push the new Docker image to the Docker registry
            - docker push $IMAGE_NAME
    CI/*:
      - step:
          image: qmesh/qmesh-containers:ubuntu1604_qgisltr_gmsh304
          script:
            #- git pull origin master
            - make install
            - make test
  custom: #Custom pipelines are triggered manually
    test_on_ubuntu16.04_qgisltr_gmsh3.0.4:
      - step:
          image: qmesh/qmesh-containers:ubuntu1604_qgisltr_gmsh304
          script:
            - make install
            - make test
    deploy_on_pypi:
      - step:
          image: qmesh/qmesh-containers:ubuntu1604_qgisltr_gmsh304
          script:
            # install twine
            - pip install twine 
            # Get the git sha key of qmesh
            - echo `git rev-parse HEAD` > GIT_SHA_KEY
            # Create a source distribution
            - python setup.py sdist
            # create pypirc file
            - echo '[pypi]' > $HOME/.pypirc
            - echo 'username = '$PYPI_USERNAME >> $HOME/.pypirc
            - echo 'password = '$PYPI_PASSWORD >> $HOME/.pypirc
            # Upload to pypi
            - twine upload dist/*
