#    Copyright (C) 2013 Alexandros Avdis and others. See the AUTHORS file for a full list of copyright holders.
#
#    This file is part of qmesh-cli.
#
#    qmesh-cli is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    qmesh-cli is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with qmesh-cli.  If not, see <http://www.gnu.org/licenses/>.


# enable Docker.
options:
  docker: true

pipelines:
  default:
  branches:
    master:
      - step:
          caches:
            # Cache directory where all docker images are stored.
            - /var/lib/docker/
          script:
            # Set IMAGE_NAME to output docker image tag
            - export IMAGE_NAME=qmesh/qmesh-containers:qmesh-cli100_ubuntu1604_qgisltr_gmsh304
            # Build container (install qmesh, qmesh-cli and test qmesh cli)
            - docker build -t $IMAGE_NAME ./tests/
            # authenticate with the Docker Hub registry
            - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
            # push the new Docker image to the Docker registry
            - docker push $IMAGE_NAME
    CI/*:
      - step:
          caches:
            # Cache directory where all docker images are stored.
            - /var/lib/docker/
          script:
            # Set IMAGE_NAME to output docker image tag
            - export IMAGE_NAME=qmesh/qmesh-containers:qmesh-cli100_ubuntu1604_qgisltr_gmsh304
            # Build container (install qmesh and test)
            - docker build -t $IMAGE_NAME ./tests/
